[live]
title = "MyMusicTaste ─ Live"
url = "https://www.mymusictaste.com/live/"
entrySelector = "section.aiup0d-5.dUvocB div.aiup0d-3.brCWqn a.jasviq-0.hwUOqz.aiup0d-2.hvxfNC"
titleSelector = "h3.sc-1sxlxw0-4.kfJLAM"
linkSelector = "*"
contentSelector = "p.sc-1sxlxw0-5.ffZpFc"
imageSelector = "div.sc-1b180qo-0.ikRoLt img"
waitUntil = "networkidle"

[news]
title = "MyMusicTaste ─ News"
url = "https://www.mymusictaste.com/news/"
entrySelector = "a.rqcvb3-0.bqnFnw"
titleSelector = "p.sc-1s0c55l-0.xoxJZ.rqcvb3-3.jcARht"
linkSelector = "*"
contentSelector = "p.sc-1s0c55l-0.QcWa.rqcvb3-4.bKeGDw"
dateSelector = "p.sc-1s0c55l-0.xoxJZ.rqcvb3-5.jacBoP span"
dateFormat = "yyyy-MM-dd'T'HH:mm:ss"
imageSelector = "div.rqcvb3-1.cJtcEg img"
waitUntil = "networkidle"

[events]
title = "MyMusicTaste ─ Events"
url = "https://www.mymusictaste.com/events/"
entrySelector = "div.sc-1gve1aw-4.dmxrqe div.sc-1gve1aw-5.coDfdi div.sc-1gve1aw-6.jRjbeR section.sc-1sxlxw0-0.sc-1y7b7pa-4.cnsQRo.bYhZXJ"
titleSelector = "h3.sc-1sxlxw0-4.sc-1y7b7pa-9.kfJLAM.ijmVUi"
linkSelector = "*"
contentSelector = "div.sc-1sxlxw0-2.sc-1y7b7pa-6.sc-1y7b7pa-7.bGSncp.gXmNjR.ePhmBG"
imageSelector = "div.sc-1b180qo-0.ikRoLt img"
waitUntil = "networkidle"

[shop]
title = "MyMusicTaste ─ Shop"
url = "https://www.mymusictaste.com/projects/"
entrySelector = "div.sy4999-4.iJbziK a.sc-1hifrd3-0.eGPdlv.sy4999-3.uBaSe"
titleSelector = "h3.sc-1sxlxw0-4.kfJLAM"
linkSelector = "*"
contentSelector = "p.sc-1sxlxw0-5.ffZpFc"
imageSelector = "div.sc-1b180qo-0.ikRoLt img"
waitUntil = "networkidle"
